name: CI

on:
  pull_request_review:
    types: [submitted, edited]
    branches:
      - '*'

jobs:
  build-frontend:
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create environment directory
        run: mkdir -p client/src/environments
      - name: Setup environment variables
        run: |
          echo 'export const environment = {
            production: true,
            firebaseConfig: {
              apiKey: "FAKE_API_KEY",
              authDomain: "fake-auth-domain.firebaseapp.com",
              projectId: "fake-project-id",
              storageBucket: "fake-project-id.appspot.com",
              messagingSenderId: "1234567890",
              appId: "1:1234567890:web:fakeappid",
              measurementId: "G-FAKEMEASUREID"
            },
            baseUrl: "http://localhost:3269/api/v1/",
            encryptionKey: "a1b2c3d4e5f6g7h8"
          };' > client/src/environments/environment.ts
          echo 'export const environment = {
            production: true,
            firebaseConfig: {
              apiKey: "FAKE_API_KEY",
              authDomain: "fake-auth-domain.firebaseapp.com",
              projectId: "fake-project-id",
              storageBucket: "fake-project-id.appspot.com",
              messagingSenderId: "1234567890",
              appId: "1:1234567890:web:fakeappid",
              measurementId: "G-FAKEMEASUREID"
            },
            baseUrl: "http://localhost:3269/api/v1/",
            encryptionKey: "a1b2c3d4e5f6g7h8"
          };' > client/src/environments/environment.development.ts
      - name: Install dependencies
        run: |
          cd client
          npm install --force
      - name: Build frontend
        run: |
          cd client
          npm run build
  build-backend:
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Setup environment variables
        run: echo "FAKE_ENV_VARIABLES" > .env
      - name: Build backend
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests
